server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
